name: Release

on:
  create:
    tags:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: make

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      with:
        name: ${{ env.GITHUB_REF }}
        files:
          - sleepysh_linux_amd64
          - sleepysh_linux_arm64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      

    

      
